### ISSUE TITLE
How to extract cell names with matched sub-clusters?

### ISSUE THREAD

**Issue by Cacti-Jiang** [semraulab/phiclust#2]
Hi, 
I am wondering how to extract cell names with matched sub-clusters? The main function "phiclust" outputs some measures of clusterability including variable genes, would it be possible to get the sub-clustering results directly from phiclust? Or should we subcluster with tools like 'Seurat' ? Then how to compare the variance-driving genes in the gene-singular vectors with DEGs of subclustering? Thanks!

**Comment by semraulab** [comment]
Hi!
sorry for the late reply. Phiclust does not do sub-clustering, it is purely a measure of clusterability. We suggest sub-clustering the clusters with high phiclust using a well-established method, like Seurat. The variance driving genes give you an indication of the biological variability in the cluster to make it easier to decide whether to sub-cluster. For example, if the variances indicate cell-cycle differences you could choose not to sub-cluster them.

**Comment by Cacti-Jiang** [comment]
Thanks a lot, that really helped!
